### ISSUE TITLE
Image in keyframes not generate into sprite sheet

### ISSUE THREAD

**Issue by dqmmpb** [MadLittleMods/gulp-css-spriter#6]
Hi, I use this gulp plugin generate sprite sheet. But the image in keyframes (I use css3 animation).The css not change, like below:
```css
@keyframes good-morning {
  0% {
    background-image: url("../../images/animation/a1.png");
  }
  14.28571429% {
    background-image: url("../../images/animation/a2.png");
  }
  28.57142857% {
    background-image: url("../../images/animation/a3.png");
  }
  42.85714286% {
    background-image: url("../../images/animation/a4.png");
  }
  57.14285714% {
    background-image: url("../../images/animation/a5.png");
  }
  71.42857143% {
    background-image: url("../../images/animation/a6.png");
  }
  85.71428571% {
    background-image: url("../../images/animation/a7.png");
  }
  100% {
    background-image: url("../../images/animation/a1.png");
  }
}
```
so, i fork the source code and add rule.type with keyframes [map-over-styles-and-transform-background-image-declarations.js](https://github.com/dqmmpb/gulp-css-spriter/blob/master/lib/map-over-styles-and-transform-background-image-declarations.js). The code is below: 
```javascript
if(rule.type === 'keyframes') {
	// Get keyframe from keyframes
	rule.keyframes = transformMap(rule.keyframes, function(keyframe, keyframeIndex, keyframes) {
		// Get declarations from keyframe
		keyframe.declarations = transformMap(keyframe.declarations, function(declaration, declarationIndex, declarations) {
			// Clone the declartion to keep it immutable
			var transformedDeclaration = extend(true, {}, declaration);
			transformedDeclaration = attachInfoToDeclaration(declarations, declarationIndex);

			// background-image always has a url
			if(transformedDeclaration.property === 'background-image') {
				return cb(transformedDeclaration, declarationIndex, declarations);
			}
			// Background is a shorthand property so make sure `url()` is in there
			else if(transformedDeclaration.property === 'background') {
				var hasImageValue = spriterUtil.backgroundURLRegex.test(transformedDeclaration.value);

				if(hasImageValue) {
					return cb(transformedDeclaration, declarationIndex, declarations);
				}
			}

			// Wrap in an object so that the declaration doesn't get interpreted
			return {
				'value': transformedDeclaration
			};
		});

	});
}
```
Now, the css will be:
```css
@keyframes good-morning {
	0% {
		background-image: url("../../images/spritesheet.png");
		background-position: -0px -0px;
	}

	14.28571429% {
		background-image: url("../../images/spritesheet.png");
		background-position: -180px -0px;
	}

	28.57142857% {
		background-image: url("../../images/spritesheet.png");
		background-position: -360px -0px;
	}

	42.85714286% {
		background-image: url("../../images/spritesheet.png");
		background-position: -540px -0px;
	}

	57.14285714% {
		background-image: url("../../images/spritesheet.png");
		background-position: -0px -300px;
	}

	71.42857143% {
		background-image: url("../../images/spritesheet.png");
		background-position: -180px -300px;
	}

	85.71428571% {
		background-image: url("../../images/spritesheet.png");
		background-position: -360px -300px;
	}

	100% {
		background-image: url("../../images/spritesheet.png");
		background-position: -0px -0px;
	}
}
```
Hope to merge or fix this bug.
